### ISSUE TITLE
Send correct x-ms headers

### ISSUE THREAD

**Issue by roeap** [Azure/azure-kusto-rust#15]
https://docs.microsoft.com/en-us/azure/data-explorer/kusto/api/rest/request#request-headers

**Comment by AsafMah** [comment]
@roeap If you ever have the time to look at the new PRs that would be nice.
We will try to get an inside team to work on this project on this semester, though.

**Comment by roeap** [comment]
Sorry, somehow I never got notified, or missed it. Will look into that right away,

**Comment by roeap** [comment]
> We will try to get an inside team to work on this project on this semester, though.

This would be excellent :)
