### ISSUE TITLE
Hang in execute_command when connecting to server

### ISSUE THREAD

**Issue by angrytoastt** [Azure/azure-kusto-rust#30]
Hello, 

I am currently loving the library for dealing with Kusto. Recently I have found an issue when using "execute_command" with await where the client just hangs and never comes back causing my application to permanently sit in a blocking state. Are there any timeouts I can set to prevent this?I have tested "server_timeout" with "ClientRequestProperties" and that does no appear to work. Any thoughts on how to solve this ?

Note: I am using execute_command over execute_query to update table data.

Thank you in advance

**Comment by angrytoastt** [comment]
I was able tor trigger an error message after adjusting some server settings (some info sanitized)

`Failed to execute query: AzureError(Error { context: Full(Custom { kind: Io, error: Error { context: Full(Custom { kind: Io, error: reqwest::Error { kind: Request, url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("place.net")), port: None, path: "/v1/rest/mgmt", query: None, fragment: None }, source: hyper::Error(Connect, ConnectError("dns error", Os { code: 11001, kind: Uncategorized, message: "No such host is known." })) } }, "failed to execute `reqwest` request") } }, "retry policy expired and the request will no longer be retried") })`

**Comment by AsafMah** [comment]
Hey, I merged in the updated version of the azure library that solves the issue @krishanjmistry mentioned.
Can you try again with the latest master?

**Comment by angrytoastt** [comment]
I am still testing some things, it now looks like its honoring the client query timeout, but I am still doing more testing and will update this thread when I can confirm more.

**Comment by AsafMah** [comment]
I'm closing for now - feel free to reopen if you still encounter the issue.
